version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: sample_db
    ports:
      - "5432:5432"
  web:
#for local
#    build: .
#for aws
    image: 301581196284.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest
    command: >
            sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - static_volume:/app/staticfiles
    environment:
      DATABASE_URL: postgresql://testuser:testpassword@postgres:5432/sample_db
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
